cuda: True
batch_size: 32
epochs: 32
learning_rate: 0.0002
momentum: 0.8
beta1: 0.5
beta2: 0.5
L1_lambda: 0.01
dataset: 'data/preprocessed/filtered_dataset.csv'
saved_embeddings: 'results/'
label_dict: 'data/preprocessed/label_dict.pkl'
saved_models: 'weights/'
model_name: 'pseudoUNET_PatchGAN'
epoch_count: 1
niter_decay: 100
niter: 100
lr_decay_iters: 50
test_split: 0.1
dropout: 0.5
seed: 42